### ISSUE TITLE
Dark theme on desktop

### ISSUE THREAD

**Issue by devyboy** [xenohunter/bluesky-overhaul#1]
# Dark theme on desktop
Currently only the mobile app has a dark theme whereas desktop users are stuck using the default light theme. 

You can enable a temporary dark theme in the Settings -> Storybook but it looks unfinished and resets when you leave the settings. Hoping to extend that into a functional dark theme.

![Screenshot 2023-04-12 at 10 12 13 AM](https://user-images.githubusercontent.com/15957811/231484804-f689a326-87de-4cef-a3a2-d8619301fb15.png)

**Comment by xenohunter** [comment]
Closing this issue since the Bluesky team implemented a Light/Dark theme switcher (in the column on the right).
