### ISSUE TITLE
dist folder missing from latest build

### ISSUE THREAD

**Issue by SelonNerias** [xenohunter/bluesky-overhaul#3]
The latest build (v1.2.1) does not include the dist folder, which is needed to install the package.

It is fixable without dev support by grabbing the dist folder from the previous build and pasting it in the main folder.

**Comment by xenohunter** [comment]
Additionally, I made sure that all commits would be built from now on. See the changes here: https://github.com/xenohunter/bluesky-overhaul/commit/54ccc59821f96fd1edfc1cb92a11de03157ef2ae.

Can I close the issue?

**Comment by SelonNerias** [comment]
Oops, I messed up the numbers. I meant v1.2.2. Yes, in the zip folder. Sorry for the mess up.

**Comment by SelonNerias** [comment]
Oh yeah your right, I probably did download the source code folder, my bad. I could have sworn I didn't, but the overhaul map certainly has the dist folder. Thanks for the assistance.

**Comment by xenohunter** [comment]
You're welcome!
