### ISSUE TITLE
Show a posts exact date and time 

### ISSUE THREAD

**Issue by haideralipunjabi** [xenohunter/bluesky-overhaul#32]
I would like to request a feature where one can hover on the relative date/time and it shows the exact time of posting.

Also, do you accept PRs? I might work on this myself if I can find some time 😀

**Comment by xenohunter** [comment]
This is a great idea, thank you!

Yes, PRs are welcome, only I'm now migrating the project to TypeScript (will likely finish today). Once that is completed, feel free to contribute, here are the [brief recommendations](https://github.com/xenohunter/bluesky-overhaul#development) (I think what you're planning to do would be a `Watcher`). I can also implement that myself if you don't have much time for that.
