### ISSUE TITLE
focus + keybinds for common tasks

### ISSUE THREAD

**Issue by cameronblandford** [xenohunter/bluesky-overhaul#37]
Desired behavior:
- be able to tab or arrow-down through posts on the skyline
- fave, repost, or mute user with keybinds

**Comment by xenohunter** [comment]
I'm now implementing it in #14, will try to add all of these there.

**Comment by xenohunter** [comment]
Most of it has been implemented in #38 and can be installed with [this release](https://github.com/xenohunter/bluesky-overhaul/releases/tag/v1.5.0). The only remained feature that is not ready is muting, which is mentioned in #39. Closing now to avoid duplicate issues.
