### ISSUE TITLE
bad ux on dark mode

### ISSUE THREAD

**Issue by Inconn** [xenohunter/bluesky-overhaul#51]
i prefer to use dark mode and there are two things i have issues with:

1. the emoji button in new posts is always black so you can't see it in dark mode.
2. you can't see what skeet you have focused with vim keybinds if you have dark mode on.

**Comment by xenohunter** [comment]
Hey! Thank you for the issue, I will try to find some time soon and fix those.

**Comment by xenohunter** [comment]
1. The emoji picker has been added by the Bluesky team, so I deleted my implementation.
2. Fixed in 8d141c82b33f5a1be0b3b4d661f8057b6395b3e1, will be rolled out soon.
