### ISSUE TITLE
Can't type on post box with shortcuts on after latest Bluesky update

### ISSUE THREAD

**Issue by Skellingtor** [xenohunter/bluesky-overhaul#55]
The extension takes priority over the typing of words and only the shortcuts work, the rest of the extension and Bluesky work as intended.

https://github.com/xenohunter/bluesky-overhaul/assets/19526287/3c127280-10df-4eb2-93f1-67557748aab0

**Comment by xenohunter** [comment]
Hey! Thank you for reporting it, I will hopefully fix it over the weekend.
